#SPDX-License-Identifier: MIT-0
---
- name: Get user info
  ansible.builtin.getent:
    database: passwd
    key: "{{ gitea_user }}"

- name: store the user info
  ansible.builtin.set_fact:
    user_info: >-
      {{
        ansible_facts.getent_passwd.get(gitea_user, [])
      }}

- name: store the user info
  ansible.builtin.set_fact:
    gitea_user_name: "{{ gitea_user }}"
    gitea_user_gid: "{{ user_info[2] }}"
    gitea_user_home: "{{ user_info[4] }}"
    gitea_user_shell: "{{ user_info[5] }}"

- name: Lookup gid name
  changed_when: false
  ansible.builtin.command:
    cmd: "getent group {{ gitea_user_gid }}"
  register: command_handle

- name: FIXME Set host variable(s) and fact(s).
  ansible.builtin.set_fact:
    gitea_user_group: "{{ command_handle.stdout | split(':') | first }}"

- name: Read remote Gitea configuration
  ansible.builtin.slurp:
    src: "{{ gitea_conf }}"
  register: gitea_app_ini_raw
  become: true
  no_log: true

- name: Parse Gitea configuration
  ansible.builtin.set_fact:
    gitea_app_ini_text: >-
      {{
        gitea_app_ini_raw.content
        | ansible.builtin.b64decode
      }}
  no_log: true

- name: Parse Gitea configuration
  ansible.builtin.set_fact:
    gitea_app_ini: >-
      {{
        (
          '[gitea_global]' ~ '\n' ~ 
          gitea_app_ini_text
        )
        | community.general.from_ini
      }}
  no_log: true

- name: Parse Gitea configuration
  ansible.builtin.set_fact:
    gitea_server_work_path: "{{ gitea_app_ini['gitea_global']['WORK_PATH'] }}"
    gitea_server_run_user: "{{ gitea_app_ini['gitea_global']['RUN_USER'] }}"

- name: Parse Gitea configuration
  ansible.builtin.set_fact:
    gitea_server_bin_path: "{{ gitea_server_work_path }}/bin"
    gitea_server_download_path: "{{ gitea_server_work_path }}/download"
    gitea_server_backup_path: "{{ gitea_server_work_path }}/backup"
